In [1]:
import numpy as np

In [2]:
# Vector
array_1d = np.array([1,2,3,4,5,6])
array_1d

array([1, 2, 3, 4, 5, 6])

In [3]:
array_1d.dtype

dtype('int32')

In [4]:
# Matrix
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Tensors

array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
array_2d.shape

(3, 3)

In [7]:
array_1d.shape

(6,)

In [8]:
array_3d.shape

(2, 2, 2)

In [9]:
array_2d.size

9

In [10]:
array_1d.size

6

In [11]:
array_2d.dtype

dtype('int32')

In [12]:
array_1d[0]

1

In [13]:
array_1d[-2]

5

In [14]:
array_1d[3:6]

array([4, 5, 6])

In [15]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
array_2d[1, :2]

array([4, 5])

In [17]:
arr_X = np.arange(1, 17)
arr_X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [18]:
arr_X_2D = arr_X.reshape(4, 4)
arr_X_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
arr_2 = arr_X_2D.flatten()
arr_2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a_b = a + b
a_b

array([5, 7, 9])

In [21]:
a - b

array([-3, -3, -3])

In [22]:
a + b

array([5, 7, 9])

In [23]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = np.array([1, 0, 1])

In [24]:
c + d

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

In [25]:
sqr = np.sqrt(a)
sqr

array([1.        , 1.41421356, 1.73205081])

In [26]:
np.log10(1000)

3.0

In [27]:
a.dot(b)

32

In [28]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [29]:
np.cross(a, b)

array([-3,  6, -3])

In [30]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
matrix_T = matrix.T
matrix_T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [32]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

In [33]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
array2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [35]:
concatenated_rows = np.concatenate((array1, array2), axis=0)

In [36]:
concatenated_rows

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
concatenated_cols = np.concatenate((array1, array2), axis=1)
concatenated_cols

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [41]:
split_arrays = np.split(concatenated_rows, 2, axis=0)
split_arrays

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [42]:
array = np.array([1, 2, 3, 4, 5])
inserted = np.insert(array, 2, [10, 20, 30])
inserted

array([ 1,  2, 10, 20, 30,  3,  4,  5])

In [43]:
deleted = np.delete(array, [1, 2])

In [44]:
deleted

array([1, 4, 5])

In [45]:
inserted

array([ 1,  2, 10, 20, 30,  3,  4,  5])

In [46]:
np.argmax(inserted)

4

0